version: '2'
services:
    node1:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node1
            - PEERS=["node2"]
        volumes:
            - ./all_data/saved_data_client_1:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node2:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node2
            - PEERS=["node1"]
        volumes:
            - ./all_data/saved_data_client_2:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node3:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node3
            - PEERS=["node7"]
        volumes:
            - ./all_data/saved_data_client_3:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node4:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node4
            - PEERS=["node1","node5"]
        volumes:
            - ./all_data/saved_data_client_4:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node5:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node5
            - PEERS=["node2"]
        volumes:
            - ./all_data/saved_data_client_5:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node6:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node6
            - PEERS=["node2"]
        volumes:
            - ./all_data/saved_data_client_6:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
    node7:
        build: ./peer/
        environment:
            - PYTHONUNBUFFERED=1
            - ORIGIN=node7
            - PEERS=["node2"]
        volumes:
            - ./all_data/saved_data_client_7:/usr/thisdocker/dataset:rw
        ports:
            - "5555"
